services:
  fastapi:
    container_name: B2B_fastapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - .:/app
    restart: always
    command: > 
      bash -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload --workers 1 --log-level info"


  postgres:
    container_name: B2B_postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: clientflow
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: singapore
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: